src/Entity/Messages.php
<?php

namespace App\Entity;

use App\Entity\User;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\MessagesRepository;

/**
 * @ORM\Entity(repositoryClass=MessagesRepository::class)
 */
class Messages
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="text")
     */
    private $message;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\Column(type="boolean")
     */
    private $is_read = 0;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="sent")
     * @ORM\JoinColumn(nullable=false)
     */
    private $sender;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="received")
     * @ORM\JoinColumn(nullable=false)
     */
    private $recipient;

    public function __construct()
    {
        // gestion de la date qui prendra la date de la création du message
        date_default_timezone_set('Europe/Paris');
        $this->created_at = new \DateTime();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getMessage(): ?string
    {
        return $this->message;
    }

    public function setMessage(string $message): self
    {
        $this->message = $message;

        return $this;
    }

    public function getCreatedAt(): ?\DateTime
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTime $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getIsRead(): ?bool
    {
        return $this->is_read;
    }

    public function setIsRead(bool $is_read): self
    {
        $this->is_read = $is_read;

        return $this;
    }

    public function getSender(): ?User
    {
        return $this->sender;
    }

    public function setSender(?User $sender): self
    {
        $this->sender = $sender;

        return $this;
    }

    public function getRecipient(): ?User
    {
        return $this->recipient;
    }

    public function setRecipient(?User $recipient): self
    {
        $this->recipient = $recipient;

        return $this;
    }
}

src/Controller/MyAccountController.php
<?php

namespace App\Controller;
use App\Repository\AnnoncesRepository;
use App\Repository\CategoriesRepository;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class MyAccountController extends AbstractController
{
    /**
     * @Route("/my/account", name="my_account")
     */
    public function index(AnnoncesRepository $annoncesRepository): Response
    {
        // récupéré l'id de l'utilisateur courant
        $id_User = $this->getUser()->getId();
        //dd($user);

        if (isset($id_User) && !empty($id_User)) {
            // $annonces = $annoncesRepository->findBy(["linkAnnonce" => $id_User, "valide" => "1"], ["date" => "DESC"]);
            $annonces = $annoncesRepository->findBy(["linkAnnonce" => $id_User], ["date" => "DESC"]);

        } else {
            $id_User = null;
            return $this->redirectToRoute('home');
        }
        return $this->render('my_account/index.html.twig', [
            'annonces' => $annonces,
            'id_User' => $id_User,
            //'response' => $response, pour gérer les réponse plus tard
            'controller_name' => 'MyAccountController',
        ]);
    }

}

templates/my_account/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Page personnelle - Les bonnes annonces{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

	<div class="example-wrapper">
		<h1 class="text-center">Page personnelle</h1>
	</div>
    <div id="avatar">
         <img src="../../assets/img/avatarUser/{{id_User}}.jpg" alt="">
    </div>

<div class="d-flex flex-md-wrap flex-sm-wrap">
  <section id="annonces" class="col-lg-6 col-md-12 col-sm-12 mb-3">
    <h3 class="text-center">Mes annonces</h3>
  	<div>
  	{# image catégorie selection voir plus tard #}
  	{# <img src={{ asset("assets/img/categorie/{{item.linkCategorie.id}}.jpg") }} alt=""> #}

  	</div>
  	{# variable de différenciation des popUP #}
  	{% set popUpNumber = 1 %}
  	{% for item in annonces | slice(0,4) %}
      {# <pre>
  	</pre> #}

  	<div class="card card-centrer global mb-2 divMyAccount">
  		{# <img class="card-img-top" src="#" alt="#"> #}
  		<div class="card-body">
        <p class="card-text text-center">{{ item.linkCategorie.categorie }} <img src="../../assets/img/logo/{{item.linkCategorie.id}}.png" alt="{{ item.linkCategorie.categorie }}"></p>
  		<h5 class="card-title">Titre : {{ item.annonces }}</h5>
        <p class="card-text">Annonce : {{ item.description }}</p>
  			<p class="card-title">De : {{ item.linkAnnonce.prenom }}</p>
  			<p class="card-text">posté le : {{ item.date ? item.date|date('d/m/Y à h:i') }} heures </p>
			<p class="card-text">Annonce visible
			{% if item.valide == 0 %}
			❌
			{% elseif item.valide == 1 %}
			✅
			{% endif %}
			</p>

  			{# <p class="card-text">{{ item.linkCategorie.categorie }}</p>
  			<p class="card-text">{{ item.linkCategorie.id }}</p>
  			<img src="../../assets/img/categorie/{{item.linkCategorie.id}}.jpg" alt="{{ item.linkCategorie.categorie }}"> #}
  			{# <a href="{{ path('annonces_show', {'id': item.id}) }}" class="btn btn-primary">Plus d'info...</a> #}
		<a href="{{ path('annonces_edit', {'id': item.id}) }}" class="btn btn-primary">Modifier</a></a>
		{{ include('annonces/_delete_form.html.twig') }}
        {# <a href="{{ path('annonces_delete', {'id': item.id}) }}" title="supprimer" class="ml-3"><img id="trash" src="../../assets/img/logo/trash.png" alt="Logo supprimer"></a> #}
  			{# <a href="registration.php" class="btn btn-primary">Inscrivez-vous !</a> #}
  			{# <p>pop numéro {{ popUpNumber }}</p> #}
  		</div>
  	</div>


  	{# incréemntation  différenciation des popUP #}
  	{% set popUpNumber = (popUpNumber + 1) %}
  {% endfor %}
    <a href="{{ path ('list') }}" class="btn btn-primary auto">Toutes mes annonces</a>
  </section>

  <section id="response" class="col-lg-6 col-md-12 col-sm-12 mb-3">
    <h3 class="text-center">Mes messages</h3>
  	<div>
  	{# image catégorie selection voir plus tard #}
  	{# <img src={{ asset("assets/img/categorie/{{item.linkCategorie.id}}.jpg") }} alt=""> #}

  	</div>
  	{# variable de différenciation des popUP #}

  	{#  for item in annonces | slice(0,4) %} #}

  {% for message in app.user.received | slice(0,4) %}
    {% if message.isRead == 0 %}
      {% set bold = "fw-bold" %}
    {% else %}
      {% set bold = "" %}
    {% endif %}
    <div class="card card-centrer global mb-2 divMyAccount">
  		{# <img class="card-img-top" src="#" alt="#"> #}
  		<div class="card-body">
        <p class="card-text text-center">Titre du message : "{{ message.title }}"" </p>
  			<h5 class="card-title">De : "{{ message.sender.email }}"</h5>
  			<p class="card-title">A : "{{ message.recipient.email }}"</p>
  			<p class="card-text">reçu le : {{ message.createdAt|date('d/m/Y à h:i')  }}  </p>
  			<p class="card-text"> {{ message.message }}</p>
        <a href="{{ path("read", {id: message.id}) }}" id="suite{{popUpNumber}}" class="btn btn-primary">Afficher</a>
        <a href="{{ path("delete", {id: message.id, "MessageSup":"MessageSup" }) }}" title="supprimer" class="ml-3"><img id="trash" src="../../assets/img/logo/trash.png" alt="Logo supprimer"></a>

  		</div>
  	</div>
  {% endfor %}
  <a href="{{ path ('messages') }}" class="btn btn-primary auto">Tous mes messages</a>
  </section>
</div>


{# déclare le nombre de popUp généré dans le script #}
<script> popUpNumber = {{ popUpNumber }} </script>


{% endblock %}